server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
      url: jdbc:mysql://192.168.1.54:3306/sso?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
  ## Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    database: 0
    host: 192.168.1.54
    port: 6379
    password:
    timeout: 3s
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 0
        max-wait: 3s

logging:
  path: D:\logs\dafusion\auth-center